### ISSUE TITLE
Bug: !stats command can be used by anyone even if they don't have the role specified in config

### ISSUE THREAD

**Issue by lbzepoqo** [IgnisAlienus/SquadJS-Player-Stats#3]
![image](https://github.com/IgnisAlienus/SquadJS-Player-Stats/assets/49586590/51033691-e1d2-4cfa-af7b-17b068e5e96d)

**Comment by IgnisAlienus** [comment]
Temporary Band-aide for this until I can deep dive would be to set the command to something that would be harder to guess.

**!postdailystats** or something even more random.

**Comment by IgnisAlienus** [comment]
Bug found and fixed. In Beta now.
